server.port=${PORT:3000}
server.address=${HOST:0.0.0.0}
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/ledger}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:postgres}
spring.sql.init.mode=always
spring.jackson.serialization.write-dates-as-timestamps=false

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD:}
spring.cache.type=redis

exchange.rate.api.url=${EXCHANGE_RATE_API_URL:https://open.er-api.com/v6/latest/}
